### ISSUE TITLE
SDL3 checklist

### ISSUE THREAD

**Issue by capehill** [AmigaPorts/SDL#33]
- [x] Use "SDL3/xyz.h" path for public SDL3 headers in AmigaOS 4 files.
- [x] Check timer code (nanosecond API)
- [x] Check mutex code (nanosecond API)
- [x] Check 64-bit file opening and handling
- [ ] Make filenames, function names, defines and such consistent: use amigaos4/AMIGAOS4 instead of just "os4"?
- [x] Merge changes from SDL2.26.x branch
- [x] Review Makefile.amigaos4 at the end
- [x] Cleanup config file

**Comment by capehill** [comment]
This is mostly done, need to think about naming of files/functions some more, but maybe later.
